### ISSUE TITLE
pygame.error: Couldn't open ./RPi_emu/GPIO/OFF.png

### ISSUE THREAD

**Issue by Hofei90** [blbltheworm/yarpie#2]
Hallo, erstmals vielen Dank für die schnelle Portierung zu Python3, wollte das ganze jetzt gleich mal ausprobieren. Leider bekomme ich folgenden Fehler:

`***\yarpie-master\yarpie-master\GPIO-example.py
Traceback (most recent call last):
  File "***\yarpie-master\yarpie-master\GPIO-example.py", line 1, in <module>
    import RPi_emu.GPIO as GPIO
  File "***\yarpie-master\yarpie-master\RPi_emu\GPIO\__init__.py", line 693, in <module>
    _gpioemu = emugui.emugui()
  File "***\yarpie-master\yarpie-master\RPi_emu\GPIO\emugui.py", line 213, in __init__
    self._icons = [pygame.image.load("./RPi_emu/GPIO/OFF.png"),
pygame.error: Couldn't open ./RPi_emu/GPIO/OFF.png`

Ich denke mal, das liegt daran wegen den Pfadangaben ./RPi_emu/....
Wäre es nicht besser, absolute Pfadangaben zu nutzen, bzw. den Pfad zu ermitteln und variable einsetzen?

(Ist es dir lieber hier Fehlermeldungen zu erhalten oder lieber im Pi Forum?

**Comment by blbltheworm** [comment]
Problem gelöst, die Dateien werden jetzt gefunden dank direkter Ermittlung des Pfades unter dem sich das Modul befindet.
